version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: phptest
      # MYSQL_USER: phpuser
      # MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #   - 8081:8080

volumes:
  mysql_data:

# version: '3.1'

# services:

#   db:
#     image: mysql
#     # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
#     # (this is just an example, not intended to be a production configuration)
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root123
#       MYSQL_DATABASE: phptest1
#   ports:
#     - 3306:3306

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

# version: '3.8'
# services:
#   mysql:
#     image: mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root123
#       MYSQL_DATABASE: phptest1
#       MYSQL_USER: ROOT
#       MYSQL_PASSWORD: root123
#     volumes:
#       - ./data:/var/lib/mysql
#     ports:
#       - "3306:3306"
